# Generated by Django 5.1.2 on 2024-10-23 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 12, 35, 4, 59009, tzinfo=datetime.timezone.utc)),
        ),
    ]
